///Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@example.com",
    "password": "test"
}

###login
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "test"
}
####
@token =eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNjA0ODQ4NDk4LjY5M30.8YcclOcCXLLzdLNwbR_Uiom9NtQahPWutz1C-83awp5KUhQaru1Orwr9apkMzQcabP4ocRmGXZtOGOveb0QwKQ


##############################
####SURVEYS
#############################

###Get all survey for user
GET http://localhost:8000/api/survey
Authorization: Bearer {{token}}

###Get single survey for user
GET http://localhost:8000/api/survey/5fa412600062b98d00c878a2
Authorization: Bearer {{token}}

###Create survey 
POST http://localhost:8000/api/survey
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"oh lala dsdsc est genial",
    "description": "bla dddd"
}

###Update survey 
PUT http://localhost:8000/api/survey/5fa412600062b98d00c878a2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"Survey 3"
}

###Delete survey
DELETE http://localhost:8000/api/survey/5fa412600062b98d00c878a2
Authorization: Bearer {{token}}



#############################
#######Questions
#############################

###Get Questions
GET http://localhost:8000/api/survey/5fa412600062b98d00c878a2/questions
Authorization: Bearer {{token}}

###Get Single Question
GET http://localhost:8000/api/question/5fa4283200cab21b00945df9
Authorization: Bearer {{token}}


###Create question 
POST http://localhost:8000/api/question/5fa412600062b98d00c878a2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "Is bla",
    "type": "choice",
    "required": false,
    "data": {
        "multiple": true,
        "answers": [
            "A nazi",
            "A baba-cool ",
            "An ecolo-bobo",
            "Both ?"
        ]
    }
}
###Update question 
PUT http://localhost:8000/api/question/5fa56dfa0084ab3e00961170
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "When was Js created ?",
    "type": "text",
    "required": true,
    "data": {
        "multiple": false,
        "answers": [
            "I like it very much",
            "I like it ",
            "I dont like it",
            "Pouah"
        ]
    }
}

###Delete survey
DELETE http://localhost:8000/api/question/5fa4264d004cf05e00d6460c
Authorization: Bearer {{token}}

